# Generated by Django 4.0 on 2022-06-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_addstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='addhealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('bloodgroup', models.CharField(max_length=200, null=True)),
                ('drinkingwater', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('regularperiods', models.CharField(max_length=200, null=True)),
                ('mentalissues', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
