# Generated by Django 4.0 on 2022-06-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0004_crud_remove_addhealth_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='addhealth',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
