# Generated by Django 3.1.7 on 2022-07-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0006_auto_20220728_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='addhealth',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
