# Generated by Django 3.1.7 on 2022-07-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0007_addhealth_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addhealth',
            name='email',
        ),
        migrations.AddField(
            model_name='addhealth',
            name='sid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='addstudent',
            name='sid',
            field=models.IntegerField(null=True),
        ),
    ]
