# Generated by Django 3.1.7 on 2022-07-28 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0008_auto_20220728_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addstudent',
            name='admissionNo',
        ),
    ]
